### ISSUE TITLE
String.h

### ISSUE THREAD

**Issue by sbhornjr** [BryceCubes/Assignment-1-Part-2#4]
Hey guys, the assignment says that Queue should support both Object and String. Could you add a String.h header file (we used Thomas' implementation from this piazza post: https://piazza.com/class/k51bluky59n2jr?cid=330 - it seems like the best spec)? Also, since Objects don't have any distinguishing features aside from their pointer values, and since the Queue will likely copy values that it receives into a new memory address, won't your tests never pass? It might make more sense to run these tests on Strings instead of Objects after you make a String.h class, unless I'm missing something about how Objects work.

Thanks, let me know.

**Comment by ZhichaoC** [comment]
1. Sure, we will add a string.h file.
2. We did not specify anything about the whether queue should copy values or point to values. And object.h is empty and up to you to implement. Anyway, I will change tests to string so that it would be much easier for you to work with.
