### ISSUE TITLE
Is there a reason that StrQueue doesn't publicly inherit from Queue?

### ISSUE THREAD

**Issue by dorothysyu** [BryceCubes/Assignment-1-Part-2#7]
The methods and constructors from StrQueue aren't accessible in the test file unless the StrQueue class declaration looks like this:
`class StrQueue: public Queue {
	public:
        ....`

**Comment by ZhichaoC** [comment]
It should, thanks for pointing out

**Comment by dorothysyu** [comment]
The class is also missing a semicolon at the end ! I think it ultimately doesn't matter since it's gonna be our file ran against your test file, but just letting you know
