### ISSUE TITLE
Small Issues, Google Test, Pull Request

### ISSUE THREAD

**Issue by sbhornjr** [BryceCubes/Assignment-1-Part-2#8]
Hey guys, we were implementing the Queue and encountered some errors that we needed to fix, which we took the liberty of doing, so just change the following things in your spec so that our implementation matches it:

- StrQueue needs to have the public keyword under the class definition
- StrQueue needs to publicly inherit from Queue like this:
       class StrQueue() : public Queue {}
- semicolon at the end of the StrQueue class
- the destructor in the Object class should be virtual
- the methods (including destructor) in StrQueue should not be virtual

We also asked about your tests on Piazza (question 388). The ones that fail (peeking when empty, etc.) will terminate the tests and not allow any of them to run anymore. It looks like you need to implement Google Test with ASSERT_EXIT functionality so that the tests may pass. There is a whole Piazza post posted by the instructors that explains how to set up Google Test (question 338). 

I am also about to make a pull request that builds upon one of the tests you wrote (testing when queues are not equal as well as when they are equal), so just incorporate that into the Google Test tests that you create. Thanks in advance.

**Comment by sbhornjr** [comment]
Ok so I don't think we can actually make the changes unless you added us as collaborators so just add a couple of lines to Test5 that tests that they are not equal at some point instead of us doing the pull request. Thanks

**Comment by sbhornjr** [comment]
Found some other errors in your tests:

- For the o2 in your test1, you don't delete it at the end of the test (line 15).
- Every time you dequeue or peek an element, you must also delete that element or else there will be a memory leak. For example, in test1 at line 24, you do q->peek()->equals(o). Instead, you must do String* s = q->peek(), then check that s->equals(o), then delete s. This must happen everywhere that you peek or dequeue.

**Comment by ZhichaoC** [comment]
Hi, I will follow the instruction to include google test library and modify tests accordingly after class (around 9:00pm).

**Comment by ZhichaoC** [comment]
I have updated the repo. The instruction to compile the program is available in piazza (search google test). If that doesn't work, please let me know. I will leave this issue open until you confirm it's working.

**Comment by sbhornjr** [comment]
Thanks. We got google test running, but when we run make, we are getting a large amount of errors saying "... was not declared in this scope", with the ... being replaced with stuff like nullptr and even a bunch of things in gtest folders. Do you have any idea whats going on here?

**Comment by sbhornjr** [comment]
I've looked around on Google and people say to use -std=gnu++11 instead of -std=c++11, but I don't see where to do that with Google Test and i also don't know if that is allowed in this class.

**Comment by ZhichaoC** [comment]
1. Can you take a screenshot of the error message?
2. What os you are running on?
3. Can you double check the makefile it generated to make sure it make sense?

**Comment by sbhornjr** [comment]
Here is the image of the errors in the terminal. There are many, MANY more than this:

<img width="770" alt="image" src="https://user-images.githubusercontent.com/31835354/73415992-79fe3880-42e1-11ea-9522-ce8f05a83a95.png">

I am running on Linux, on a VM on the Khoury machines.

The makefile honestly doesn't make much sense to me, but I wouldn't know what it should look like anyway. It seems like it's probably right.

**Comment by ZhichaoC** [comment]
Can you verify in the makefile that the compiling command that --std=c++11, it looks to me nullptr is not found may indicate missing that flag in make command. If that's the case, we can look into how to modify cmake file to make it include this flag

**Comment by ZhichaoC** [comment]
The potential problem can be:
Khoury machines has cmake version 2.8.12.2
However, "set(CMAKE_CXX_STANDARD 11)" in CMakeLists.txt only works for cmake 3.1 (https://stackoverflow.com/questions/10851247/how-do-i-activate-c-11-in-cmake).
So, two ways to accomplish this:
1. Upgrade cmake
2. Replace  "set(CMAKE_CXX_STANDARD 11)" with "add_definitions(-std=c++11)"
Let me know if it still doesn't work.

**Comment by sbhornjr** [comment]
Hey, so I did the second option there and it worked. However, in running the tests, there were phantom seg faults that should not have been there. I realized that the tests were not set up correctly; if you look at the Piazza post about google test (I saw that you commented on it), the tests should be actually run in TEST functions, with the main function running RUN_ALL_TESTS. I fixed the composition of the file and it all works now, do you want me to just send you the file or paste it here so that our test files match up with each other?

**Comment by ZhichaoC** [comment]
Yes, it would be really helpful. Thanks.

**Comment by sbhornjr** [comment]
Indenting might be messed up, I don't know why some of it is registering as code and some isn't, but here I just copy and pasted the whole file. It includes a little bit that we added in Test5 to test when queues are not equal and other times where we needed to do delete statements after dequeueing/peeking (see Test1):

//lang::CwC

#include "queue.h"
#include <stdio.h>
#include <gtest/gtest.h>

// test basic behaviors
void Test1() {
    bool result = true;
    StrQueue* q = new StrQueue(5);
    // test allocated size and current size
    result &= (q->current_size() == 0);
    result &= (q->allocated_size() == 5);

    String* o = new String("hello");
    String* o2 = new String("world");

    // test enqueue
    q->enqueue(o);
    q->enqueue(o2);
    result &= (q->current_size() == 2);
    result &= (q->allocated_size() == 5);

    String* s = q->peek();

    // test peek
    result &= (s->equals(o));
    result &= (q->current_size() == 2);
    result &= (q->allocated_size() == 5);

    delete s;

    String* st = q->dequeue();

    // test dequeue
    result &= (st->equals(o));
    result &= (q->current_size() == 1);
    result &= (q->allocated_size() == 5);

    delete st;

    // test clear
    q->clear();
    result &= (!(q->isFull()));
    result &= (q->isEmpty());

    // test is full and is empty
    q->enqueue(o);
    q->enqueue(o);
    q->enqueue(o);
    q->enqueue(o);
    q->enqueue(o);

    result &= (q->current_size() == 5);
    result &= (q->allocated_size() == 5);

    result &= (q->isFull());
    result &= (!(q->isEmpty()));
    delete q;
    delete o;
    delete o2;
    if (result) {
      exit(0);
    }
    exit(4);
}

TEST(W1, Test1) {
    ASSERT_EXIT(Test1(), ::testing::ExitedWithCode(0), ".*");
}

// test enqueue more elements than allocated size
void Test2() {
    Queue* q = new Queue(5);

    Object* o = new Object();

    q->enqueue(o);
    q->enqueue(o);
    q->enqueue(o);
    q->enqueue(o);
    q->enqueue(o);
    q->enqueue(o);

    delete q;
    delete o;
    exit(0);
}

TEST(W1, Test2) {
    ASSERT_EXIT(Test2(), ::testing::ExitedWithCode(1), ".*");
}

// test dequeue empty queue
void Test3() {
    Queue* q = new Queue(5);

    q->dequeue();

    delete q;
    exit(0);
}

TEST(W1, Test3) {
    ASSERT_EXIT(Test3(), ::testing::ExitedWithCode(2), ".*");
}

// test peek empty queue
void Test4() {
    Queue* q = new Queue(5);

    q->peek();

    delete q;
    exit(0);
}

TEST(W1, Test4) {
    ASSERT_EXIT(Test4(), ::testing::ExitedWithCode(3), ".*");
}

// test equal and hash
void Test5() {
    bool result = true;
    StrQueue* q1 = new StrQueue(5);
    StrQueue* q2 = new StrQueue(4);

    String* o = new String("hello");
    String* o2 = new String("goodbye");

    q1->enqueue(o);
    q2->enqueue(o);

    result &= (q1->equals(q2));
    result &= (q1->hash() == q2->hash());

    q2->enqueue(o2);

    result &= (!q1->equals(q2));
    result &= (q1->hash() != q2->hash());

    q1->clear();
    q2->clear();

    q1->enqueue(o);
    q2->enqueue(o2);

    result &= (!q1->equals(q2));
    result &= (q1->hash() != q2->hash());

    printf("%d\n", result);

    delete q1;
    delete q2;
    delete o;
    delete o2;
    if (result) {
      exit(0);
    }
    exit(4);
}

TEST(W1, Test5) {
  ASSERT_EXIT(Test5(), ::testing::ExitedWithCode(0), ".*");
}

int main(int argc, char** argv)
{
    testing::InitGoogleTest(&argc, argv);
    return RUN_ALL_TESTS();
}
